#!/bin/bash
# Guía final de configuración de branding con logo oficial de Neogenesys

echo "🎨 CONFIGURACIÓN FINAL - BRANDING NEOGENESYS OFICIAL"
echo "===================================================="

echo ""
echo "✅ LOGO OFICIAL SUBIDO CORRECTAMENTE"
echo "===================================="
echo "• Logo actualizado con la imagen oficial proporcionada"
echo "• Nombre corregido: 'Neogenesys' (todo junto)"
echo "• Incluye badge '25 Años'"

echo ""
echo "🔧 CONFIGURACIÓN EXACTA EN AUTHENTIK"
echo "===================================="

echo ""
echo "📍 UBICACIÓN: https://34.68.124.46:9443/if/admin/"
echo "📍 RUTA: System > Tenants > authentik-default (Edit)"

echo ""
echo "📋 CONFIGURACIÓN EN 'BRANDING SETTINGS':"
echo "┌─────────────────────────────────────────────────────────┐"
echo "│ Domain: authentik-default                               │"
echo "│ Default: ✅ (marcado)                                  │"
echo "│                                                         │"
echo "│ BRANDING:                                               │"
echo "│ Title: Kolaboree                                        │"
echo "│ Branding title: Neogenesys                              │"
echo "│ Branding logo: /static/dist/assets/icons/brand.svg      │"
echo "│ Branding favicon: /static/dist/assets/icons/icon.svg    │"
echo "│                                                         │"
echo "│ OPTIONAL FLOWS:                                         │"
echo "│ Authentication flow: default-authentication-flow        │"
echo "│ Invalidation flow: default-invalidation-flow            │"
echo "└─────────────────────────────────────────────────────────┘"

echo ""
echo "⚠️ CORRECCIONES IMPORTANTES:"
echo "• Cambiar 'Neo Genesys' por 'Neogenesys' (todo junto)"
echo "• Usar el logo oficial que incluye el badge '25 Años'"

echo ""
echo "🎯 PASOS DETALLADOS:"
echo "=================="
echo "1. Abrir https://34.68.124.46:9443/if/admin/"
echo "2. Login como akadmin"
echo "3. Menú lateral: System > Tenants"
echo "4. Hacer clic en 'authentik-default'"
echo "5. Scroll hasta 'Branding settings'"
echo "6. Configurar EXACTAMENTE como se muestra arriba"
echo "7. Hacer clic en 'Update'"
echo "8. Esperar confirmación de guardado"

echo ""
echo "🧪 VERIFICACIÓN:"
echo "==============="
echo "1. Abrir pestaña incógnito"
echo "2. Ir a: https://34.68.124.46:9443/"
echo "3. Verificar:"
echo "   • Logo de Neogenesys aparece ✓"
echo "   • Badge '25 Años' visible ✓"
echo "   • Favicon correcto en pestaña ✓"
echo "   • Título 'Neogenesys' en página ✓"

echo ""
echo "🔄 PRUEBA COMPLETA SSO:"
echo "======================"
echo "1. Logout de Authentik"
echo "2. Ir a: https://34.68.124.46:9443/application/o/guacamole/"
echo "3. Login: soporte@kolaboree.local / Neo123!!!"
echo "4. Verificar:"
echo "   • Branding Neogenesys en login ✓"
echo "   • Acceso automático a Guacamole ✓"
echo "   • Conexiones disponibles ✓"

echo ""
echo "💡 RESULTADO ESPERADO:"
echo "====================="
echo "• Páginas de Authentik con branding oficial de Neogenesys"
echo "• Logo con badge '25 Años' visible"
echo "• Flujo SSO completo funcional"
echo "• Usuario 'soporte' accede a Guacamole sin autenticación adicional"

echo ""
echo "✅ CONFIGURACIÓN LISTA PARA PRODUCCIÓN"
echo "======================================"
echo "El sistema está configurado con:"
echo "• Branding oficial de Neogenesys ✓"
echo "• SSO Authentik → Guacamole ✓"
echo "• Usuario LDAP sincronizado ✓"
echo "• Conexiones RDP configuradas ✓"