#!/bin/bash
# Guía final para completar la integración SSO Authentik-Guacamole

echo "🎯 GUÍA FINAL: COMPLETAR INTEGRACIÓN SSO"
echo "========================================"

echo ""
echo "✅ LO QUE YA ESTÁ CONFIGURADO:"
echo "============================="
echo "• Authentik funcionando con branding Neogenesys ✓"
echo "• Usuario 'soporte' sincronizado desde LDAP ✓"
echo "• Guacamole con 7 conexiones RDP configuradas ✓"
echo "• Permisos de usuario en base de datos Guacamole ✓"
echo "• Variables OIDC configuradas en docker-compose.yml ✓"
echo "• Endpoints OIDC de Authentik funcionando ✓"

echo ""
echo "⚠️ LO QUE FALTA CONFIGURAR:"
echo "=========================="
echo "1. RAC Provider en Authentik con Client ID específico"
echo "2. Application en Authentik apuntando al Provider"
echo "3. Client Secret en docker-compose.yml"
echo "4. Reiniciar Guacamole"

echo ""
echo "🔧 PASOS DETALLADOS:"
echo "==================="

echo ""
echo "PASO 1: Configurar RAC Provider en Authentik"
echo "────────────────────────────────────────────"
echo "1. Ir a: https://34.68.124.46:9443/if/admin/"
echo "2. Login como akadmin"
echo "3. Applications > Providers > Create"
echo "4. Seleccionar: OAuth2/OpenID Provider"
echo "5. Configurar EXACTAMENTE:"
echo ""
echo "   Name: Guacamole RAC Provider"
echo "   Authentication flow: default-authentication-flow"
echo "   Authorization flow: default-provider-authorization-explicit-consent"
echo ""
echo "   Client type: Confidential"
echo "   Client ID: guacamole-rac-client"
echo "   (¡IMPORTANTE! Debe ser exactamente este ID)"
echo ""
echo "   Redirect URIs/Origins:"
echo "   http://34.68.124.46:8080/guacamole/"
echo ""
echo "   Scopes: openid,profile,email,groups"
echo "   Subject mode: Based on the User's ID"
echo "   Include claims in id_token: ✅ (marcado)"
echo ""
echo "6. Hacer clic en 'Create'"
echo "7. ¡COPIAR EL CLIENT SECRET GENERADO!"

echo ""
echo "PASO 2: Configurar Application en Authentik"
echo "──────────────────────────────────────────"
echo "1. Applications > Applications > Create"
echo "2. Configurar:"
echo ""
echo "   Name: Apache Guacamole"
echo "   Slug: guacamole"
echo "   Provider: Guacamole RAC Provider"
echo ""
echo "   Launch URL: http://34.68.124.46:8080/guacamole/"
echo "   Open in new tab: ✅ (marcado)"
echo ""
echo "   Icon: /static/dist/assets/icons/icon.svg"
echo ""
echo "3. Hacer clic en 'Create'"

echo ""
echo "PASO 3: Actualizar docker-compose.yml"
echo "────────────────────────────────────"
echo "1. Abrir: /home/infra/local_server_poc/docker-compose.yml"
echo "2. Buscar la sección 'guacamole:'"
echo "3. Agregar la línea:"
echo "   OPENID_CLIENT_SECRET: \"TU_CLIENT_SECRET_AQUI\""
echo "4. Guardar archivo"

echo ""
echo "PASO 4: Reiniciar Guacamole"
echo "──────────────────────────"
echo "1. Ejecutar: docker-compose restart guacamole"
echo "2. Esperar 30 segundos"
echo "3. Verificar: docker logs kolaboree-guacamole"

echo ""
echo "PASO 5: Probar el flujo completo"
echo "──────────────────────────────"
echo "1. Abrir pestaña incógnito"
echo "2. Ir a: https://34.68.124.46:9443/if/user/"
echo "3. Login: soporte@kolaboree.local / Neo123!!!"
echo "4. Hacer clic en 'Apache Guacamole'"
echo "5. Debería abrir Guacamole automáticamente"
echo "6. Verificar que aparezcan las conexiones RDP"

echo ""
echo "🧪 SCRIPT DE VERIFICACIÓN:"
echo "========================="
echo "Después de completar, ejecutar:"
echo "python3 /home/infra/local_server_poc/test-sso-complete.py"

echo ""
echo "🚨 SOLUCIÓN DE PROBLEMAS:"
echo "========================"
echo "Si algo no funciona:"
echo "1. Verificar logs: docker logs kolaboree-guacamole"
echo "2. Verificar logs: docker logs kolaboree-authentik-server"
echo "3. Comprobar que Client ID sea exactamente: guacamole-rac-client"
echo "4. Verificar que Redirect URI sea: http://34.68.124.46:8080/guacamole/"

echo ""
echo "✅ RESULTADO ESPERADO:"
echo "====================⬆"
echo "• Usuario hace login una sola vez en Authentik"
echo "• Click en Apache Guacamole lo lleva directo a las conexiones"
echo "• No necesita autenticarse nuevamente en Guacamole"
echo "• Ve sus conexiones RDP disponibles"
echo "• Puede conectarse a Windows Server sin password adicional"

echo ""
echo "🎉 ¡SSO AUTHENTIK-GUACAMOLE COMPLETO!"
echo "====================================="