#!/bin/bash
# Guía paso a paso para crear la aplicación RAC en Authentik

echo "🎯 SOLUCIÓN: CREAR APLICACIÓN RAC EN AUTHENTIK"
echo "=============================================="

echo ""
echo "✅ DIAGNÓSTICO CONFIRMADO:"
echo "• RAC Provider configurado correctamente ✓"
echo "• Authentik interfaz funcionando ✓"
echo "• Guacamole con OIDC configurado ✓"
echo "❌ FALTA: Application en Authentik"

echo ""
echo "🔧 PASOS EXACTOS PARA SOLUCIONAR:"
echo "================================="

echo ""
echo "PASO 1: Acceder a Authentik Admin"
echo "─────────────────────────────────"
echo "1. Abrir: https://34.68.124.46:9443/if/admin/"
echo "2. Login como akadmin"

echo ""
echo "PASO 2: Crear la Application"
echo "───────────────────────────"
echo "1. En el menú lateral: Applications > Applications"
echo "2. Hacer clic en '+ Create' (botón azul)"
echo "3. Llenar el formulario EXACTAMENTE así:"
echo ""
echo "   📋 CONFIGURACIÓN EXACTA:"
echo "   ┌─────────────────────────────────────────────────┐"
echo "   │ Name: Apache Guacamole                          │"
echo "   │ Slug: guacamole                                 │"
echo "   │ Group: (dejar vacío)                            │"
echo "   │ Provider: [Seleccionar tu RAC Provider]         │"
echo "   │                                                 │"
echo "   │ BACKCHANNEL PROVIDERS: (dejar vacío)            │"
echo "   │                                                 │"
echo "   │ UI SETTINGS:                                    │"
echo "   │ Launch URL: http://34.68.124.46:8080/guacamole/ │"
echo "   │ Open in new tab: ✅ (marcado)                  │"
echo "   │                                                 │"
echo "   │ ICON:                                           │"
echo "   │ Icon: /static/dist/assets/icons/icon.svg        │"
echo "   │ (Opcional: Usar el logo de Neogenesys)         │"
echo "   └─────────────────────────────────────────────────┘"
echo ""
echo "4. Hacer clic en 'Create'"

echo ""
echo "PASO 3: Asignar permisos al usuario"
echo "──────────────────────────────────"
echo "1. Después de crear la aplicación, ir a la pestaña:"
echo "   'Policy / Group / User Bindings'"
echo "2. Hacer clic en 'Create Binding'"
echo "3. Configurar:"
echo "   • Target: User"
echo "   • User: soporte (o el usuario que quieras que tenga acceso)"
echo "   • Enabled: ✅"
echo "4. Hacer clic en 'Create'"

echo ""
echo "PASO 4: Verificar la aplicación"
echo "──────────────────────────────"
echo "1. Logout de Authentik Admin"
echo "2. Ir a: https://34.68.124.46:9443/if/user/"
echo "3. Login: soporte@kolaboree.local / Neo123!!!"
echo "4. Verificar que aparezca 'Apache Guacamole' en la lista"

echo ""
echo "PASO 5: Probar el SSO"
echo "────────────────────"
echo "1. Hacer clic en 'Apache Guacamole'"
echo "2. Debería abrir Guacamole automáticamente"
echo "3. Sin pedir credenciales adicionales"
echo "4. Mostrar las conexiones RDP disponibles"

echo ""
echo "🚨 TROUBLESHOOTING:"
echo "==================="
echo ""
echo "SI LA APLICACIÓN NO APARECE:"
echo "• Verificar que el binding del usuario esté creado"
echo "• Verificar que la aplicación esté 'Enabled'"
echo "• Logout y login nuevamente en Authentik"
echo ""
echo "SI DA ERROR AL HACER CLIC:"
echo "• Verificar Launch URL: http://34.68.124.46:8080/guacamole/"
echo "• Verificar que el Provider esté asignado correctamente"
echo "• Revisar logs: docker logs kolaboree-guacamole"
echo ""
echo "SI GUACAMOLE PIDE LOGIN:"
echo "• Verificar Client Secret en docker-compose.yml"
echo "• Verificar que OPENID_ENABLED=true"
echo "• Verificar Redirect URI en el Provider"

echo ""
echo "📋 INFORMACIÓN DE CONFIGURACIÓN:"
echo "================================"
echo "Provider Client ID: guacamole-rac-client"
echo "Provider Client Secret: (visible en docker-compose.yml)"
echo "Application Launch URL: http://34.68.124.46:8080/guacamole/"
echo "Application Slug: guacamole"

echo ""
echo "✅ DESPUÉS DE COMPLETAR ESTOS PASOS:"
echo "===================================="
echo "El flujo será:"
echo "1. Usuario → https://34.68.124.46:9443/if/user/"
echo "2. Login → Ve aplicación 'Apache Guacamole'"
echo "3. Click → Abre Guacamole con SSO"
echo "4. Acceso → Ve conexiones RDP sin login adicional"

echo ""
echo "🎉 ¡SSO AUTHENTIK-GUACAMOLE FUNCIONARÁ COMPLETAMENTE!"