#!/bin/bash
# Script para finalizar configuración OIDC en Guacamole

echo "🔧 FINALIZANDO CONFIGURACIÓN OIDC"
echo "================================="

echo "1. 📋 Estado actual de configuración:"
echo "✅ OIDC ya está configurado en docker-compose.yml"
echo "✅ Extensiones OPENID y LDAP están habilitadas"
echo "✅ Endpoints de Authentik están configurados"

echo ""
echo "2. ⚠️ FALTA CONFIGURAR:"
echo "======================"
echo "❌ OPENID_CLIENT_SECRET - necesario para completar OIDC"

echo ""
echo "3. 🎯 CONFIGURACIÓN REQUERIDA EN AUTHENTIK:"
echo "==========================================="

echo ""
echo "📋 RAC PROVIDER - CONFIGURACIÓN EXACTA:"
echo "┌─────────────────────────────────────────────────────┐"
echo "│ Name: Guacamole RAC Provider                        │"
echo "│ Client ID: guacamole-rac-client                     │"
echo "│ (DEBE coincidir con docker-compose.yml)            │"
echo "│                                                     │"
echo "│ PROTOCOL SETTINGS:                                  │"
echo "│ Client type: Confidential                           │"
echo "│ Redirect URIs/Origins:                              │"
echo "│   - http://34.68.124.46:8080/guacamole/            │"
echo "│                                                     │"
echo "│ ADVANCED PROTOCOL SETTINGS:                        │"
echo "│ Scopes: openid,profile,email,groups                │"
echo "│ Subject mode: Based on the User's ID               │"
echo "│ Include claims in id_token: ✅                     │"
echo "└─────────────────────────────────────────────────────┘"

echo ""
echo "📋 APPLICATION - CONFIGURACIÓN EXACTA:"
echo "┌─────────────────────────────────────────────────────┐"
echo "│ Name: Apache Guacamole                              │"
echo "│ Slug: guacamole                                     │"
echo "│ Provider: Guacamole RAC Provider                    │"
echo "│                                                     │"
echo "│ UI SETTINGS:                                        │"
echo "│ Launch URL: http://34.68.124.46:8080/guacamole/    │"
echo "│ Open in new tab: ✅                                │"
echo "└─────────────────────────────────────────────────────┘"

echo ""
echo "4. 📝 PASOS PARA COMPLETAR:"
echo "=========================="
echo "1. Ir a: https://34.68.124.46:9443/if/admin/"
echo "2. Applications > Providers"
echo "3. Crear/Editar RAC Provider con configuración exacta de arriba"
echo "4. ¡IMPORTANTE! Usar Client ID: guacamole-rac-client"
echo "5. Copiar el Client Secret generado"
echo "6. Actualizar docker-compose.yml con el Client Secret"
echo "7. Reiniciar Guacamole"

echo ""
echo "5. 🔍 VERIFICAR ENDPOINTS OIDC:"
echo "==============================="
curl -k -s "https://34.68.124.46:9443/application/o/guacamole/.well-known/openid-configuration" | python3 -m json.tool | head -10

echo ""
echo "6. 💡 FLUJO ESPERADO DESPUÉS DE CONFIGURAR:"
echo "==========================================="
echo "1. Usuario va a: https://34.68.124.46:9443/if/user/"
echo "2. Hace clic en 'Apache Guacamole'"
echo "3. Authentik genera token OIDC"
echo "4. Redirige a: http://34.68.124.46:8080/guacamole/?token=..."
echo "5. Guacamole valida token con Authentik"
echo "6. Guacamole autentica usuario y muestra conexiones"

echo ""
echo "✅ CONFIGURACIÓN CASI COMPLETA"
echo "=============================="
echo "Solo falta agregar OPENID_CLIENT_SECRET al docker-compose.yml"