#!/bin/bash
# Script para solucionar el problema de redirección SSO

echo "🔧 SOLUCIONANDO PROBLEMA DE REDIRECCIÓN SSO"
echo "==========================================="

echo ""
echo "📋 PROBLEMA IDENTIFICADO:"
echo "• Authentik te redirige directamente al login de Guacamole"
echo "• No pasas por el menú de aplicaciones de Authentik"
echo "• Guacamole muestra error 403 en /api/tokens"

echo ""
echo "🎯 SOLUCIÓN: Configurar el flujo correcto"
echo "========================================"

echo ""
echo "1. 📝 VERIFICAR CONFIGURACIÓN ACTUAL..."

# Verificar si Guacamole está recibiendo los parámetros OIDC
echo "Variables OIDC en Guacamole:"
docker exec kolaboree-guacamole env | grep -E "OPENID_" | while read line; do
    echo "  ✅ $line"
done

echo ""
echo "2. 🔍 VERIFICAR ENDPOINTS DE AUTHENTIK..."

# Probar acceso a Authentik user interface
echo "Probando acceso a interfaz de usuario de Authentik..."
curl -k -s -o /dev/null -w "Status: %{http_code}" "https://34.68.124.46:9443/if/user/"
echo ""

echo ""
echo "3. 🎯 URLs CORRECTAS PARA USAR:"
echo "=============================="
echo ""
echo "❌ NO USAR (te lleva directo al login de Guacamole):"
echo "   https://34.68.124.46:9443/application/o/guacamole/"
echo "   http://34.68.124.46:8080/guacamole/"
echo ""
echo "✅ USAR (interfaz de usuario de Authentik):"
echo "   https://34.68.124.46:9443/if/user/"
echo "   Desde ahí hacer clic en 'Apache Guacamole'"

echo ""
echo "4. 🔧 CONFIGURACIÓN REQUERIDA EN AUTHENTIK:"
echo "=========================================="

echo ""
echo "📋 VERIFICAR EN AUTHENTIK ADMIN:"
echo "1. Ir a: https://34.68.124.46:9443/if/admin/"
echo "2. Applications > Applications"
echo "3. Verificar que existe 'Apache Guacamole'"
echo "4. La configuración debe ser:"
echo ""
echo "   Name: Apache Guacamole"
echo "   Slug: guacamole"
echo "   Provider: [Tu RAC Provider]"
echo "   Launch URL: http://34.68.124.46:8080/guacamole/"
echo "   Open in new tab: ✅"

echo ""
echo "📋 VERIFICAR RAC PROVIDER:"
echo "1. Applications > Providers"
echo "2. Verificar configuración del Provider:"
echo ""
echo "   Client ID: guacamole-rac-client"
echo "   Client Secret: (debe coincidir con docker-compose.yml)"
echo "   Redirect URIs: http://34.68.124.46:8080/guacamole/"
echo "   Scopes: openid,profile,email,groups"

echo ""
echo "5. 🧪 FLUJO CORRECTO PARA PROBAR:"
echo "================================"
echo ""
echo "PASO 1: Ir a la interfaz de usuario"
echo "https://34.68.124.46:9443/if/user/"
echo ""
echo "PASO 2: Login con credenciales"
echo "Usuario: soporte@kolaboree.local"
echo "Password: Neo123!!!"
echo ""
echo "PASO 3: Buscar aplicación 'Apache Guacamole'"
echo "Debe aparecer en la lista de aplicaciones disponibles"
echo ""
echo "PASO 4: Hacer clic en 'Apache Guacamole'"
echo "Esto debe abrir Guacamole con SSO automático"

echo ""
echo "6. 🚨 SI SIGUE SIN FUNCIONAR:"
echo "============================"
echo ""
echo "Problema posible: La aplicación no está creada o mal configurada"
echo ""
echo "CREAR APLICACIÓN MANUALMENTE:"
echo "1. https://34.68.124.46:9443/if/admin/"
echo "2. Applications > Applications > Create"
echo "3. Configurar:"
echo "   Name: Apache Guacamole"
echo "   Slug: guacamole"
echo "   Provider: [Seleccionar tu RAC Provider]"
echo "   Launch URL: http://34.68.124.46:8080/guacamole/"

echo ""
echo "7. 📊 DIAGNÓSTICO DE LOGS:"
echo "========================="
echo "Si hay problemas, revisar logs:"
echo "docker logs kolaboree-guacamole | tail -20"
echo "docker logs kolaboree-authentik-server | tail -20"

echo ""
echo "✅ RESUMEN:"
echo "==========="
echo "• No accedas directamente a Guacamole"
echo "• Usa la interfaz de usuario de Authentik"
echo "• Haz clic en la aplicación desde el menú"
echo "• Verifica que la aplicación esté configurada correctamente"