#!/bin/bash

echo "=== CONFIGURACIÓN FORWARD AUTH PROVIDER EN AUTHENTIK ==="
echo "Este script te guiará paso a paso para configurar Forward Auth Provider"
echo ""
echo "🔗 URL de Authentik: https://34.68.124.46:9443"
echo "👤 Usuario Admin: akadmin"
echo "🔐 Password: Neogenesys123!!!"
echo ""

echo "PASO 1: Crear Forward Auth Provider"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Providers"
echo "2. Haz clic en 'Create'"
echo "3. Selecciona: 'Forward auth (single application)'"
echo ""
echo "Configuración del Provider:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Guacamole Forward Auth                     │"
echo "│ External host: http://34.68.124.46:8080         │"
echo "│ Internal host: http://kolaboree-guacamole:8080   │"
echo "│ Internal host SSL Validation: ❌ DESMARCADO     │"
echo "│ Token validity: hours=24                         │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 2: Configurar Headers Personalizados"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "En la sección 'ADVANCED PROTOCOL SETTINGS':"
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ Additional scopes: openid email profile groups            │"
echo "│ Custom headers:                                            │"
echo "│                                                            │"
echo "│ {                                                          │"
echo "│   \"X-AUTHENTIK-USERNAME\": \"user.username\",               │"
echo "│   \"X-AUTHENTIK-EMAIL\": \"user.email\",                     │"
echo "│   \"X-AUTHENTIK-NAME\": \"user.name\",                       │"
echo "│   \"X-AUTHENTIK-GROUPS\": \"user.groups\",                   │"
echo "│   \"X-AUTHENTIK-UID\": \"user.uid\"                          │"
echo "│ }                                                          │"
echo "└────────────────────────────────────────────────────────────┘"
echo ""

echo "PASO 3: Crear Aplicación"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Applications"
echo "2. Haz clic en 'Create'"
echo "3. Configuración:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Apache Guacamole Secure                    │"
echo "│ Slug: apache-guacamole-secure                    │"
echo "│ Provider: Guacamole Forward Auth                 │"
echo "│ Launch URL: http://34.68.124.46:8080/guacamole/  │"
echo "│ Icon (opcional): Upload logo si tienes           │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 4: Configurar Outpost (CRÍTICO)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Outposts"
echo "2. Selecciona el Outpost existente o crea uno nuevo"
echo "3. En 'Applications', agrega: 'Apache Guacamole Secure'"
echo "4. Configuración del Outpost:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: embedded-outpost                           │"
echo "│ Type: Forward auth (domain level)               │"
echo "│ Applications: Apache Guacamole Secure           │"
echo "│ Configuration:                                   │"
echo "│   authentik_host: https://34.68.124.46:9443     │"
echo "│   log_level: debug                               │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 5: Verificar Configuración"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a Authentik Admin → System → Tasks"
echo "2. Verifica que no hay errores"
echo "3. Prueba acceder a: http://34.68.124.46:8080/guacamole/"
echo ""

echo "PASO 6: Probar el Flujo SSO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Abre una ventana de incógnito"
echo "2. Ve a: http://34.68.124.46:8080/guacamole/"
echo "3. Deberías ser redirigido a Authentik"
echo "4. Ingresa credenciales: soporte@kolaboree.local / Neo123!!!"
echo "5. Deberías ser redirigido automáticamente a Guacamole"
echo "6. Verifica que estés logueado como 'soporte'"
echo ""

echo "💡 NOTAS IMPORTANTES:"
echo "• Si hay errores, revisa los logs: docker logs kolaboree-authentik-server"
echo "• Los headers personalizados son críticos para el funcionamiento"
echo "• El Outpost debe estar asociado a la aplicación"
echo "• Guacamole debe estar configurado con header authentication"
echo ""

echo "✅ CONFIGURACIÓN ACTUAL DE GUACAMOLE YA APLICADA:"
echo "• EXTENSION_PRIORITY: header,openid,ldap,*"
echo "• HTTP_AUTH_HEADER: X-AUTHENTIK-USERNAME"
echo "• HTTP_AUTH_NAME_ATTRIBUTE: username"
echo "• HTTP_AUTH_EMAIL_ATTRIBUTE: email"
echo "• HTTP_AUTH_AUTO_CREATE_USER: true"
echo ""

echo "🚀 ¡Después de completar estos pasos, tendrás SSO completo!"
echo "🔐 Los usuarios se autenticarán en Authentik y accederán automáticamente a Guacamole"