#!/bin/bash
# Guía paso a paso para resolver el problema de sincronización LDAP

echo "🔧 GUÍA PASO A PASO - RESOLVER PROBLEMA LDAP"
echo "============================================="

echo ""
echo "❌ PROBLEMA ACTUAL:"
echo "   'Could not find page in cache: goauthentik.io/sources/ldap/page/...'"
echo "   'Try increasing ldap.task_timeout_h    ours'"

echo ""
echo "✅ CAUSA IDENTIFICADA:"
echo "   El LDAP Source tiene una configuración incorrecta o corrupta"
echo "   que está causando timeouts en las tareas de sincronización."

echo ""
echo "🎯 SOLUCIÓN DEFINITIVA:"
echo ""

echo "PASO 1: Eliminar LDAP Source existente"
echo "──────────────────────────────────────"
echo "1. Ir a: https://34.68.124.46:9443/if/admin/"
echo "2. Hacer login como akadmin"
echo "3. Ir a: Directory > Federation & Social login > LDAP Sources"
echo "4. Si hay algún LDAP Source existente, hacer clic en ❌ Delete"
echo "5. Confirmar eliminación"
echo ""

echo "PASO 2: Crear nuevo LDAP Source"
echo "──────────────────────────────"
echo "1. En la misma página, hacer clic en ➕ Create"
echo "2. Llenar EXACTAMENTE con estos datos:"
echo ""
echo "   📋 CONFIGURACIÓN EXACTA:"
echo "   ┌─────────────────────────────────────────────────────────┐"
echo "   │ Name: Kolaboree LDAP                                    │"
echo "   │ Slug: kolaboree-ldap-new                                │"
echo "   │ Enabled: ✅ (marcado)                                  │"
echo "   │ Authentication flow: default-authentication-flow        │"
echo "   │ Enrollment flow: default-enrollment-flow                │"
echo "   │                                                         │"
echo "   │ CONNECTION SETTINGS:                                    │"
echo "   │ Server URI: ldap://kolaboree-ldap:389                  │"
echo "   │ Enable StartTLS: ❌ (desmarcado)                       │"
echo "   │ TLS Verification Certificate: (vacío)                   │"
echo "   │ Bind CN: cn=admin,dc=kolaboree,dc=local                │"
echo "   │ Bind Password: zEYgBeGPqNdqXSUF2IajtezHrjSE8tXgE8dx6Cl │"
echo "   │                                                         │"
echo "   │ LDAP ATTRIBUTE MAPPING:                                 │"
echo "   │ Base DN: dc=kolaboree,dc=local                         │"
echo "   │ Additional User DN: ou=users                           │"
echo "   │ Additional Group DN: ou=groups                         │"
echo "   │                                                         │"
echo "   │ USER:                                                   │"
echo "   │ User object filter: (objectClass=inetOrgPerson)       │"
echo "   │ User object class: inetOrgPerson                       │"
echo "   │ Object uniqueness field: uid                           │"
echo "   │                                                         │"
echo "   │ GROUP:                                                  │"
echo "   │ Group object filter: (objectClass=groupOfNames)       │"
echo "   │ Group object class: groupOfNames                       │"
echo "   │ Group membership field: member                         │"
echo "   │                                                         │"
echo "   │ SYNC SETTINGS:                                          │"
echo "   │ Sync users: ✅ (marcado)                              │"
echo "   │ Sync groups: ✅ (marcado)                             │"
echo "   │ Sync parent group: (vacío)                             │"
echo "   └─────────────────────────────────────────────────────────┘"

echo ""
echo "PASO 3: Guardar y sincronizar"
echo "────────────────────────────"
echo "1. Hacer clic en 💾 Create (guardar)"
echo "2. Esperar a que se guarde"
echo "3. En la lista de LDAP Sources, encontrar el nuevo 'Kolaboree LDAP'"
echo "4. Hacer clic en el botón 🔄 'Sync' al lado del LDAP Source"
echo "5. ESPERAR 2-3 minutos (no cerrar la página)"

echo ""
echo "PASO 4: Verificar sincronización"
echo "───────────────────────────────"
echo "1. Ir a: Directory > Users"
echo "2. Buscar el usuario 'soporte'"
echo "3. Debería aparecer con:"
echo "   • Username: soporte"
echo "   • Email: soporte@kolaboree.local" 
echo "   • Source: Kolaboree LDAP"

echo ""
echo "🔍 VERIFICACIÓN FINAL:"
echo "Si el usuario 'soporte' aparece en Directory > Users,"
echo "entonces la sincronización LDAP está funcionando correctamente."

echo ""
echo "🧪 PRUEBA DEL FLUJO COMPLETO:"
echo "1. Logout de Authentik"
echo "2. Ir a: https://34.68.124.46:9443/application/o/guacamole/"
echo "3. Debería redirigir al login de Authentik"
echo "4. Usar: soporte@kolaboree.local / Neo123!!!"
echo "5. Debería entrar a Guacamole automáticamente"

echo ""
echo "⚠️ SI EL PROBLEMA PERSISTE:"
echo "El error puede estar en:"
echo "1. Server URI incorrecto (debe ser kolaboree-ldap:389)"
echo "2. Bind Password incompleto"
echo "3. Cache corrupto (ya lo limpiamos)"

echo ""
echo "✅ RESUMEN:"
echo "1. ❌ Eliminar LDAP Source existente"
echo "2. ➕ Crear nuevo con configuración exacta"
echo "3. 🔄 Sincronizar"
echo "4. ✅ Verificar usuario en Directory > Users"

echo ""
echo "📞 Si necesitas ayuda, puedes verificar:"
echo "• Logs de Authentik: docker logs kolaboree-authentik-server"
echo "• Usuario en LDAP: ya verificado ✅"
echo "• Conectividad: ya verificada ✅"