#!/bin/bash

echo "=== CONFIGURACIÓN PROXY PROVIDER EN AUTHENTIK ==="
echo "Este script te guiará paso a paso para configurar Proxy Provider"
echo "Forward Auth no está disponible, usaremos Proxy Provider como alternativa"
echo ""
echo "🔗 URL de Authentik: https://34.68.124.46:9443"
echo "👤 Usuario Admin: akadmin"
echo "🔐 Password: Neogenesys123!!!"
echo ""

echo "PASO 1: Crear Proxy Provider"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Providers"
echo "2. Haz clic en 'Create'"
echo "3. Selecciona: 'Proxy Provider'"
echo ""
echo "Configuración del Provider:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Guacamole Proxy Provider                   │"
echo "│ Authorization flow: default-authorization-flow   │"
echo "│ External host: http://34.68.124.46:8080         │"
echo "│ Internal host: http://kolaboree-guacamole:8080   │"
echo "│ Internal host SSL Validation: ❌ DESMARCADO     │"
echo "│ Intercept header authentication: ✅ MARCADO     │"
echo "│ Token validity: hours=24                         │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 2: Configurar Headers Avanzados"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "En la sección 'ADVANCED PROTOCOL SETTINGS':"
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ Additional scopes: openid email profile groups            │"
echo "│ Mode: Forward auth (single application)                   │"
echo "│ Set HTTP-Basic Authentication: ❌ DESMARCADO              │"
echo "│ Set HTTP Authorization header: ❌ DESMARCADO              │"
echo "│ Custom headers:                                            │"
echo "│                                                            │"
echo "│ X-AUTHENTIK-USERNAME: user.username                       │"
echo "│ X-AUTHENTIK-EMAIL: user.email                             │"
echo "│ X-AUTHENTIK-NAME: user.name                               │"
echo "│ X-AUTHENTIK-GROUPS: user.groups                           │"
echo "│ X-AUTHENTIK-UID: user.uid                                 │"
echo "└────────────────────────────────────────────────────────────┘"
echo ""

echo "PASO 3: Crear Aplicación"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Applications"
echo "2. Haz clic en 'Create'"
echo "3. Configuración:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Apache Guacamole SSO                       │"
echo "│ Slug: apache-guacamole-sso                       │"
echo "│ Provider: Guacamole Proxy Provider               │"
echo "│ Launch URL: http://34.68.124.46:8080/guacamole/  │"
echo "│ Icon (opcional): Upload logo si tienes           │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 4: Configurar Outpost (CRÍTICO)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Outposts"
echo "2. Busca el outpost 'authentik Embedded Outpost' o crea uno nuevo"
echo "3. Edita el outpost existente:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: authentik Embedded Outpost                 │"
echo "│ Type: Proxy                                      │"
echo "│ Applications: Apache Guacamole SSO               │"
echo "│ Configuration:                                   │"
echo "│   authentik_host: https://34.68.124.46:9443     │"
echo "│   log_level: debug                               │"
echo "│   docker_network: null                          │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 5: Verificar Configuración"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a Authentik Admin → System → Tasks"
echo "2. Verifica que no hay errores en el outpost"
echo "3. Ve a Applications → Outposts y verifica que esté 'Healthy'"
echo ""

echo "PASO 6: Configurar Nginx (REQUERIDO PARA PROXY)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "El Proxy Provider requiere que Nginx haga la integración:"
echo ""
echo "Configuración requerida en nginx.conf:"
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ server {                                                   │"
echo "│     listen 8080;                                          │"
echo "│     server_name 34.68.124.46;                            │"
echo "│                                                            │"
echo "│     location /akprox/ {                                   │"
echo "│         proxy_pass http://authentik-server:9000;          │"
echo "│     }                                                      │"
echo "│                                                            │"
echo "│     location / {                                          │"
echo "│         auth_request /akprox/auth/guacamole;              │"
echo "│         auth_request_set \$user \$upstream_http_x_authentik_username; │"
echo "│         auth_request_set \$email \$upstream_http_x_authentik_email;   │"
echo "│         proxy_set_header X-AUTHENTIK-USERNAME \$user;    │"
echo "│         proxy_set_header X-AUTHENTIK-EMAIL \$email;      │"
echo "│         proxy_pass http://kolaboree-guacamole:8080;       │"
echo "│     }                                                      │"
echo "│ }                                                          │"
echo "└────────────────────────────────────────────────────────────┘"
echo ""

echo "PASO 7: Probar el Flujo SSO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Abre una ventana de incógnito"
echo "2. Ve a: http://34.68.124.46:8080/guacamole/"
echo "3. Deberías ser redirigido a Authentik"
echo "4. Ingresa credenciales: soporte@kolaboree.local / Neo123!!!"
echo "5. Deberías ser redirigido automáticamente a Guacamole"
echo "6. Verifica que estés logueado como 'soporte'"
echo ""

echo "💡 ALTERNATIVA SIMPLIFICADA: RAC PROVIDER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Si el Proxy Provider es muy complejo, puedes usar RAC Provider:"
echo "• RAC Provider está específicamente diseñado para RDP/SSH/VNC"
echo "• Integra directamente con Guacamole sin configuración de Nginx"
echo "• Es más simple de configurar"
echo ""
echo "¿Prefieres continuar con Proxy Provider o usar RAC Provider?"
echo ""

echo "✅ CONFIGURACIÓN ACTUAL DE GUACAMOLE YA APLICADA:"
echo "• EXTENSION_PRIORITY: header,openid,ldap,*"
echo "• HTTP_AUTH_HEADER: X-AUTHENTIK-USERNAME"
echo "• HTTP_AUTH_NAME_ATTRIBUTE: username"
echo "• HTTP_AUTH_EMAIL_ATTRIBUTE: email"
echo "• HTTP_AUTH_AUTO_CREATE_USER: true"
echo ""

echo "🚀 PRÓXIMOS PASOS:"
echo "1. Decide entre Proxy Provider (más complejo) o RAC Provider (más simple)"
echo "2. Ejecuta la configuración correspondiente"
echo "3. Prueba el flujo SSO completo"