#!/bin/bash

echo "=== CONFIGURACIÓN RAC PROVIDER EN AUTHENTIK (RECOMENDADO) ==="
echo "RAC Provider está específicamente diseñado para aplicaciones como Guacamole"
echo ""
echo "🔗 URL de Authentik: https://34.68.124.46:9443"
echo "👤 Usuario Admin: akadmin"
echo "🔐 Password: Neogenesys123!!!"
echo ""

echo "PASO 1: Crear RAC Provider"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Providers"
echo "2. Haz clic en 'Create'"
echo "3. Selecciona: 'RAC Provider'"
echo ""
echo "Configuración del Provider:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Guacamole RAC Provider                     │"
echo "│ Authorization flow: default-authorization-flow   │"
echo "│ Connection expiry: hours=24                      │"
echo "│ Delete failing connections: ✅ MARCADO           │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 2: Crear Aplicación"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Applications"
echo "2. Haz clic en 'Create'"
echo "3. Configuración:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Apache Guacamole RAC                       │"
echo "│ Slug: apache-guacamole-rac                       │"
echo "│ Provider: Guacamole RAC Provider                 │"
echo "│ Launch URL: http://34.68.124.46:8080/guacamole/  │"
echo "│ Open in new tab: ✅ MARCADO                      │"
echo "│ Icon (opcional): Upload logo si tienes           │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 3: Configurar Endpoints RAC"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Providers → Guacamole RAC Provider"
echo "2. Haz clic en la pestaña 'Endpoints'"
echo "3. Crea endpoints para tus conexiones RDP existentes:"
echo ""
echo "ENDPOINTS BASADOS EN TUS CONEXIONES ACTUALES:"
echo ""
echo "🖥️  Endpoint 1 - Windows Production:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Windows Production                         │"
echo "│ Host: 100.95.223.18                             │"
echo "│ Protocol: RDP                                    │"
echo "│ Settings:                                        │"
echo "│   Port: 3389                                     │"
echo "│   Width: 1920                                    │"
echo "│   Height: 1080                                   │"
echo "│   Color depth: 32                               │"
echo "│   Username: \${user.username}                    │"
echo "│   Password: \${user.attributes.ldap_password}    │"
echo "└──────────────────────────────────────────────────┘"
echo ""
echo "🖥️  Endpoint 2 - Windows Server Demo:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Windows Server Demo                        │"
echo "│ Host: 192.168.1.100                             │"
echo "│ Protocol: RDP                                    │"
echo "│ Settings:                                        │"
echo "│   Port: 3389                                     │"
echo "│   Username: administrator                        │"
echo "│   Password: \${user.attributes.admin_password}   │"
echo "└──────────────────────────────────────────────────┘"
echo ""
echo "🐧 Endpoint 3 - Ubuntu Server SSH:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Ubuntu Server SSH                          │"
echo "│ Host: 192.168.1.102                             │"
echo "│ Protocol: SSH                                    │"
echo "│ Settings:                                        │"
echo "│   Port: 22                                       │"
echo "│   Username: admin                                │"
echo "│   Password: \${user.attributes.ssh_password}     │"
echo "└──────────────────────────────────────────────────┘"
echo ""
echo "🖼️  Endpoint 4 - Linux Desktop VNC:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Linux Desktop VNC                          │"
echo "│ Host: 192.168.1.101                             │"
echo "│ Protocol: VNC                                    │"
echo "│ Settings:                                        │"
echo "│   Port: 5901                                     │"
echo "│   Password: \${user.attributes.vnc_password}     │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 4: Configurar Property Mappings"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Customization → Property Mappings"
echo "2. Busca mappings de tipo 'RAC Provider'"
echo "3. Verifica que existan estos mappings esenciales:"
echo "   • authentik default RAC Mapping: Username"
echo "   • authentik default RAC Mapping: Password"
echo ""
echo "Si no existen, créalos:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Username Mapping:                                │"
echo "│   Name: RAC Username Mapping                     │"
echo "│   Type: RAC Provider                             │"
echo "│   Expression: user.username                      │"
echo "│                                                  │"
echo "│ Password Mapping:                                │"
echo "│   Name: RAC Password Mapping                     │"
echo "│   Type: RAC Provider                             │"
echo "│   Expression: user.attributes.get('ldap_password', '')  │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 5: Configurar LDAP para obtener passwords"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Directory → Sources"
echo "2. Busca tu LDAP source existente"
echo "3. En 'Property mappings', asegúrate de incluir:"
echo "   • authentik default LDAP Mapping: password"
echo ""
echo "Si no existe, créalo:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: LDAP Password Mapping                      │"
echo "│ Type: LDAP Source                                │"
echo "│ LDAP Property: userPassword                      │"
echo "│ User Property: attributes.ldap_password          │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 6: Configurar Outpost"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Outposts"
echo "2. Busca el outpost existente o crea uno nuevo"
echo "3. Configuración:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: authentik Embedded Outpost                 │"
echo "│ Type: RAC                                        │"
echo "│ Applications: Apache Guacamole RAC               │"
echo "│ Configuration:                                   │"
echo "│   authentik_host: https://34.68.124.46:9443     │"
echo "│   log_level: debug                               │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 7: Probar el Flujo SSO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a la interfaz de usuario de Authentik: https://34.68.124.46:9443/if/user/"
echo "2. Ingresa credenciales: soporte@kolaboree.local / Neo123!!!"
echo "3. Verás la aplicación 'Apache Guacamole RAC' en tu dashboard"
echo "4. Haz clic en la aplicación"
echo "5. Deberías ver los endpoints RDP disponibles"
echo "6. Haz clic en un endpoint para conectarte"
echo ""

echo "💡 VENTAJAS DE RAC PROVIDER:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Diseñado específicamente para RDP/SSH/VNC"
echo "✅ Maneja automáticamente credenciales"
echo "✅ No requiere configuración de Nginx"
echo "✅ Integración nativa con LDAP"
echo "✅ Interfaz de usuario optimizada para conexiones remotas"
echo "✅ Gestión centralizada de endpoints"
echo ""

echo "🔄 MIGRACIÓN DE CONEXIONES EXISTENTES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Tus 7 conexiones RDP existentes en Guacamole se pueden:"
echo "• Mantener como están (acceso directo a Guacamole)"
echo "• Migrar a RAC Provider (acceso unificado vía Authentik)"
echo "• Usar ambos métodos simultáneamente"
echo ""

echo "🚀 RECOMENDACIÓN:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "RAC Provider es la mejor opción para tu caso de uso porque:"
echo "1. Cumple exactamente tu requerimiento de SSO"
echo "2. Maneja automáticamente las credenciales LDAP"
echo "3. Proporciona una interfaz unificada"
echo "4. Es más fácil de configurar que Proxy Provider"
echo ""

echo "✅ PRÓXIMO PASO:"
echo "Configura RAC Provider siguiendo esta guía paso a paso"