#!/bin/bash

echo "=== CONFIGURACIÓN RAC PROVIDER - VERSIÓN HÍBRIDA ==="
echo "Implementación SIN ROMPER tus conexiones existentes de Guacamole"
echo ""
echo "🔗 URL de Authentik: https://34.68.124.46:9443"
echo "👤 Usuario Admin: akadmin"
echo "🔐 Password: Neogenesys123!!!"
echo ""

echo "🎯 ESTRATEGIA HÍBRIDA RECOMENDADA:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Mantener Guacamole actual funcionando (http://34.68.124.46:8080/guacamole/)"
echo "✅ Agregar RAC Provider para SSO y gestión centralizada"
echo "✅ Los usuarios pueden usar ambos sistemas"
echo "✅ Migración gradual según conveniencia"
echo ""

echo "PASO 1: Crear RAC Provider"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Providers"
echo "2. Haz clic en 'Create'"
echo "3. Selecciona: 'RAC Provider'"
echo ""
echo "Configuración del Provider:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Remote Access Provider                     │"
echo "│ Authorization flow: default-authorization-flow   │"
echo "│ Connection expiry: hours=24                      │"
echo "│ Delete failing connections: ✅ MARCADO           │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 2: Crear Aplicación"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Applications"
echo "2. Haz clic en 'Create'"
echo "3. Configuración:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: Remote Desktop Access                      │"
echo "│ Slug: remote-desktop-access                      │"
echo "│ Provider: Remote Access Provider                 │"
echo "│ Launch URL: (dejar vacío)                        │"
echo "│ Open in new tab: ✅ MARCADO                      │"
echo "│ Icon (opcional): Upload logo si tienes           │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 3: Configurar Endpoints - TUS CONEXIONES REALES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Providers → Remote Access Provider"
echo "2. Haz clic en la pestaña 'Endpoints'"
echo "3. Crea estos 4 endpoints basados en tu infraestructura:"
echo ""

echo "🖥️  ENDPOINT 1: Windows Production (100.95.223.18)"
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ Name: Windows Production Server                            │"
echo "│ Host: 100.95.223.18                                       │"
echo "│ Protocol: RDP                                              │"
echo "│ Settings (clic en 'Show advanced'):                       │"
echo "│   Port: 3389                                               │"
echo "│   Width: 1920                                              │"
echo "│   Height: 1080                                             │"
echo "│   Color depth: 32                                          │"
echo "│   DPI: 96                                                  │"
echo "│   Username: soporte                                        │"
echo "│   Password: Neo123!!!                                      │"
echo "│   (o usar \${user.attributes.ldap_password} si está configurado) │"
echo "└────────────────────────────────────────────────────────────┘"
echo ""

echo "🖥️  ENDPOINT 2: Windows Server Demo (192.168.1.100)"
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ Name: Windows Server Demo                                  │"
echo "│ Host: 192.168.1.100                                       │"
echo "│ Protocol: RDP                                              │"
echo "│ Settings:                                                  │"
echo "│   Port: 3389                                               │"
echo "│   Username: administrator                                  │"
echo "│   Password: [tu password de administrator]                 │"
echo "└────────────────────────────────────────────────────────────┘"
echo ""

echo "🐧 ENDPOINT 3: Ubuntu Server SSH (192.168.1.102)"
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ Name: Ubuntu Server SSH                                    │"
echo "│ Host: 192.168.1.102                                       │"
echo "│ Protocol: SSH                                              │"
echo "│ Settings:                                                  │"
echo "│   Port: 22                                                 │"
echo "│   Username: admin                                          │"
echo "│   Password: [tu password de admin]                        │"
echo "│   Terminal type: xterm-256color                           │"
echo "└────────────────────────────────────────────────────────────┘"
echo ""

echo "🖼️  ENDPOINT 4: Linux Desktop VNC (192.168.1.101)"
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ Name: Linux Desktop VNC                                    │"
echo "│ Host: 192.168.1.101                                       │"
echo "│ Protocol: VNC                                              │"
echo "│ Settings:                                                  │"
echo "│   Port: 5901                                               │"
echo "│   Password: [tu password de VNC]                          │"
echo "│   Color depth: 24-bit                                     │"
echo "└────────────────────────────────────────────────────────────┘"
echo ""

echo "PASO 4: Configurar Property Mappings (SI ES NECESARIO)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Solo si quieres usar credenciales dinámicas desde LDAP:"
echo "1. Ve a: Customization → Property Mappings"
echo "2. Verifica que existan mappings de tipo 'RAC Provider'"
echo "3. Si no existen, no es crítico para la funcionalidad básica"
echo ""

echo "PASO 5: Configurar Outpost"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: Applications → Outposts"
echo "2. Busca 'authentik Embedded Outpost' o crea uno nuevo"
echo "3. Edita la configuración:"
echo "┌──────────────────────────────────────────────────┐"
echo "│ Name: authentik Embedded Outpost                 │"
echo "│ Type: RAC                                        │"
echo "│ Applications: Remote Desktop Access              │"
echo "│ Configuration (YAML):                            │"
echo "│   authentik_host: https://34.68.124.46:9443     │"
echo "│   log_level: debug                               │"
echo "│   docker_network: null                          │"
echo "└──────────────────────────────────────────────────┘"
echo ""

echo "PASO 6: Probar el Flujo SSO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a: https://34.68.124.46:9443/if/user/"
echo "2. Login: soporte@kolaboree.local / Neo123!!!"
echo "3. Verás 'Remote Desktop Access' en tu dashboard"
echo "4. Haz clic en la aplicación"
echo "5. Deberías ver los 4 endpoints disponibles"
echo "6. Haz clic en 'Windows Production Server' para probar"
echo ""

echo "🌟 VENTAJAS DE ESTA CONFIGURACIÓN:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ HTML5: SÍ, usa HTML5 Canvas en el navegador"
echo "✅ Dinámico: SÍ, completamente escalable para más usuarios"
echo "✅ Sin romper: Guacamole actual sigue funcionando normalmente"
echo "✅ SSO: Un solo login para acceder a todas las conexiones"
echo "✅ Centralizado: Gestión de usuarios y conexiones desde Authentik"
echo "✅ Auditable: Logs completos de quién accede a qué"
echo ""

echo "🔄 COMPARACIÓN DE ACCESOS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "MÉTODO ACTUAL (Guacamole directo):"
echo "• http://34.68.124.46:8080/guacamole/"
echo "• Login individual en Guacamole"
echo "• Gestión manual de usuarios"
echo ""
echo "MÉTODO NUEVO (RAC Provider):"
echo "• https://34.68.124.46:9443/if/user/"
echo "• Login único con credenciales LDAP"
echo "• Gestión automática desde Authentik"
echo ""

echo "🎯 RECOMENDACIÓN:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Implementa RAC Provider con tus 4 conexiones principales"
echo "Mantén Guacamole como respaldo durante la transición"
echo "Evalúa la experiencia de usuario antes de migrar completamente"
echo ""
echo "🚀 ¿LISTO PARA IMPLEMENTAR?"
echo "Sigue estos pasos y tendrás SSO funcionando en 15-20 minutos"