#!/bin/bash

echo "🔐 CONFIGURACIÓN MANUAL DE AUTHENTIK PARA GUACAMOLE"
echo "=================================================="
echo ""
echo "1. 🌐 Accede a Authentik Admin:"
echo "   URL: https://34.68.124.46:9443/if/admin/"
echo "   Usuario: akadmin"
echo "   Password: Kolaboree2024!Admin"
echo ""
echo "2. 🏗️  Crear OAuth2/OpenID Provider:"
echo "   Applications → Providers → Create"
echo "   - Type: OAuth2/OpenID Provider"
echo "   - Name: Guacamole RAC Provider"
echo "   - Authentication flow: default-authentication-flow"
echo "   - Authorization flow: default-provider-authorization-explicit-consent"
echo "   - Client type: Confidential"
echo "   - Client ID: guacamole-rac-client"
echo "   - Client secret: guacamole-rac-secret-2024"
echo "   - Redirect URIs (one per line):"
echo "     http://34.68.124.46:8080/guacamole/"
echo "     http://34.68.124.46:8080/guacamole/api/ext/oidc/callback"
echo "   - Sub mode: Based on the User's hashed ID"
echo "   - Include claims in id_token: ✅ Enabled"
echo ""
echo "3. 📱 Crear Aplicación:"
echo "   Applications → Applications → Create"
echo "   - Name: Guacamole RAC"
echo "   - Slug: guacamole-rac"
echo "   - Provider: [Seleccionar el provider recién creado]"
echo "   - Launch URL: http://34.68.124.46:8080/guacamole/"
echo "   - Open in new tab: ✅ Enabled"
echo ""
echo "4. 🔄 Reiniciar Guacamole:"
echo "   docker-compose restart guacamole"
echo ""
echo "5. 🧪 Probar integración:"
echo "   - Ir a: https://34.68.124.46:9443/if/flow/default-authentication-flow/"
echo "   - Hacer login con akadmin"
echo "   - Hacer clic en la aplicación 'Guacamole RAC'"
echo "   - Debería redirigir a Guacamole ya autenticado"
echo ""
echo "📋 DETALLES TÉCNICOS PARA REFERENCIA:"
echo "====================================="
echo "Client ID: guacamole-rac-client"
echo "Client Secret: guacamole-rac-secret-2024"
echo "Authorization Endpoint: http://34.68.124.46:9000/application/o/authorize/"
echo "Token Endpoint: http://34.68.124.46:9000/application/o/token/"
echo "JWKS Endpoint: http://34.68.124.46:9000/application/o/guacamole-rac/jwks/"
echo "Issuer: http://34.68.124.46:9000/application/o/guacamole-rac/"